Repository aakanksha215/Java-Practice-1, pull requests merged in 2022-10, with the labels that each got.

#1 hacktoberfest-2022
  Java Exercise/Sample.java
Labels: hacktoberfest-2022

#3 hacktoberfest-2022
  Java 2/Example.java
Labels: hacktoberfest-2022, hactoberfest-2022

#4 hacktoberfest-2022
  Java 1/MinMax.java
Labels: hacktoberfest-2022, hactoberfest-2022

#6 Java Basic Programs
  Java Basic Programs/ASCII_of_Character.java
  Java Basic Programs/A_to_Z_Print.java
  Java Basic Programs/Adding2Numbers.java
  Java Basic Programs/Average_Mark.java
  Java Basic Programs/Calculating_Power.java
  Java Basic Programs/Count_Number_of_Digit.java
  Java Basic Programs/EvenNumberInRange.java
  Java Basic Programs/Factorial_of_Number.java
  Java Basic Programs/Greatest_Num_Amoung3.java
  Java Basic Programs/HelloWorld.java
  Java Basic Programs/Max_Number.java
  Java Basic Programs/Max_Number_Input.java
  Java Basic Programs/Min_Number.java
  Java Basic Programs/Min_Number_Input.java
  Java Basic Programs/Natural_Numbers.java
  Java Basic Programs/OddEven.java
  Java Basic Programs/OddNumberInRange.java
  Java Basic Programs/Print_Char.java
  Java Basic Programs/Sum2Numbers.java
  Java Basic Programs/Sum_Natural_Numbers.java
  Java Basic Programs/Sum_Odd_or_Even.java
  Java Basic Programs/UserInput.java
  Java Basic Programs/Vowel_or_Constant.java
Labels: hactoberfest-2022
